version: "3.9"
services:
  glowing-telegram:
    restart: always
    env_file:
      - ./.env
    build:
      context: ../.
      dockerfile: glowing-telegram/Dockerfile
    stdin_open: true
    tty: true

volumes:
  glowing-telegram:
